"""Core Memory Compiler: generate injectable context files from learned patterns.

Compiling memory into loadable context is an established pattern; our compiler's
difference is what it compiles FROM — human rulings and Golden Rules with
provenance, not raw memory — so the output is governed law, not a summary.
Mount Helicon compiles its highest-confidence memories, review patterns, and
playbook rules into files that agents automatically load:

1. core-memory.md   - Top N most useful memories, always in context
2. skill files      - Task-specific rules from playbook feedback
3. CLAUDE.md patch  - Suggested additions to project instructions

The compiler runs after significant events (batch reviews, triage runs)
and outputs files agents can consume without calling Mount Helicon's MCP tools.
"""

import json
import os
import sqlite3
from datetime import datetime, timezone

from helicon.playbooks import TASK_CATEGORIES, get_playbooks, build_playbooks


def compile_core_memory(conn: sqlite3.Connection, max_items: int = 20) -> str:
    """Compile the most important memories into a compact block.

    Selection: approved cubes ranked by (confidence * q_value * recency).
    Output: markdown block ready to inject into system prompts.
    """
    rows = conn.execute(
        "SELECT gc.id, gc.title, gc.type, gc.source, gc.confidence, gc.content, "
        "gc.created_at, gc.review_count "
        "FROM helicon_cubes gc "
        "WHERE gc.review_status = 'approved' AND gc.merged_into IS NULL "
        "AND gc.confidence > 0.3 "
        "ORDER BY gc.confidence DESC, gc.review_count DESC "
        f"LIMIT {max_items * 3}"
    ).fetchall()

    if not rows:
        return "# Core Memory\n\nNo approved memories yet. Review items to build core memory.\n"

    try:
        q_values = {}
        q_rows = conn.execute(
            "SELECT cube_id, q_value FROM memory_utility"
        ).fetchall()
        q_values = {r["cube_id"]: r["q_value"] for r in q_rows}
    except Exception:
        q_values = {}

    now = datetime.now(timezone.utc).replace(tzinfo=None)
    scored = []
    for r in rows:
        q = q_values.get(r["id"], 0.5)
        try:
            raw = r["created_at"].replace("Z", "").split("+")[0]
            age_days = (now - datetime.fromisoformat(raw)).days
            recency = max(0.1, 1.0 - age_days * 0.01)
        except (ValueError, TypeError):
            recency = 0.5

        score = r["confidence"] * 0.4 + q * 0.35 + recency * 0.25
        scored.append({"row": r, "score": score, "q": q})

    scored.sort(key=lambda x: x["score"], reverse=True)
    selected = scored[:max_items]

    lines = ["# Core Memory", "", f"_Compiled {now.strftime('%Y-%m-%d %H:%M')} UTC "
             f"| {len(selected)} items | Mount Helicon auto-generated_", ""]

    by_type = {}
    for s in selected:
        t = s["row"]["type"]
        if t not in by_type:
            by_type[t] = []
        by_type[t].append(s)

    for t, items in sorted(by_type.items()):
        lines.append(f"## {t.title()}")
        for s in items:
            r = s["row"]
            content = (r["content"] or "")[:200].replace("\n", " ").strip()
            conf = f"{r['confidence']:.0%}"
            lines.append(f"- **{r['title'][:60]}** ({conf}) - {content}")
        lines.append("")

    return "\n".join(lines)


def compile_skill_file(conn: sqlite3.Connection, category: str) -> str | None:
    """Generate a skill file for a task category from playbook data."""
    playbooks = get_playbooks(conn)
    if not playbooks:
        playbooks = build_playbooks(conn)

    target = None
    for pb in playbooks:
        if pb["category"] == category:
            target = pb
            break

    if not target:
        return None

    rules = target.get("feedback_rules", [])
    stats = target.get("review_stats", {})

    lines = [
        f"# {target['label']} Skill",
        "",
        f"_Auto-generated by Mount Helicon from {len(rules)} feedback rules "
        f"and {stats.get('reviewed', 0)} reviews._",
        "",
    ]

    if stats.get("reviewed", 0) > 0:
        lines.append("## Review Patterns")
        lines.append(f"- Ship rate: {stats.get('ship_rate', 0):.0%}")
        lines.append(f"- Kill rate: {stats.get('kill_rate', 0):.0%}")
        lines.append(f"- Total reviewed: {stats.get('reviewed', 0)}")
        lines.append("")

    if rules:
        lines.append("## Rules (from review history)")
        for r in rules:
            rule_text = r.get("rule", "")[:150].replace("\n", " ").strip()
            if rule_text:
                lines.append(f"- {rule_text}")
        lines.append("")

    cat = TASK_CATEGORIES.get(category, {})
    tags = cat.get("tags", [])
    if tags:
        lines.append("## Trigger Tags")
        lines.append(f"Activate when task involves: {', '.join(tags)}")
        lines.append("")

    return "\n".join(lines)


def compile_all_skills(conn: sqlite3.Connection) -> dict:
    """Generate skill files for all categories."""
    results = {}
    for cat_key in TASK_CATEGORIES:
        content = compile_skill_file(conn, cat_key)
        if content:
            results[cat_key] = content
    return results


def compile_claude_md_patch(conn: sqlite3.Connection) -> str:
    """Generate a CLAUDE.md section with Mount Helicon-learned rules."""
    playbooks = get_playbooks(conn)
    if not playbooks:
        playbooks = build_playbooks(conn)

    lines = [
        "## Mount Helicon Memory Rules (auto-generated)",
        "",
        "Rules learned from review history. Do not edit manually.",
        "",
    ]

    for pb in playbooks:
        rules = pb.get("feedback_rules", [])
        if not rules:
            continue
        lines.append(f"### {pb['label']}")
        for r in rules[:5]:
            rule_text = r.get("rule", "")[:120].replace("\n", " ").strip()
            if rule_text:
                lines.append(f"- {rule_text}")
        lines.append("")

    return "\n".join(lines)


def write_compiled_files(conn: sqlite3.Connection, output_dir: str) -> dict:
    """Write all compiled files to disk."""
    os.makedirs(output_dir, exist_ok=True)
    written = {}

    core = compile_core_memory(conn)
    core_path = os.path.join(output_dir, "core-memory.md")
    with open(core_path, "w") as f:
        f.write(core)
    written["core-memory.md"] = len(core)

    skills = compile_all_skills(conn)
    for cat_key, content in skills.items():
        filename = f"skill-{cat_key}.md"
        path = os.path.join(output_dir, filename)
        with open(path, "w") as f:
            f.write(content)
        written[filename] = len(content)

    patch = compile_claude_md_patch(conn)
    patch_path = os.path.join(output_dir, "claude-md-patch.md")
    with open(patch_path, "w") as f:
        f.write(patch)
    written["claude-md-patch.md"] = len(patch)

    return {
        "output_dir": output_dir,
        "files_written": len(written),
        "files": written,
        "total_bytes": sum(written.values()),
    }


def inject_into_claude_code(conn: sqlite3.Connection) -> dict:
    """Auto-inject compiled files into Claude Code's skill directory.

    Writes:
    - ~/.claude/skills/helicon-*.md  (skill files per category)
    - Appends Mount Helicon section to project CLAUDE.md if it exists
    """
    home = os.path.expanduser("~")
    skills_dir = os.path.join(home, ".claude", "skills")
    os.makedirs(skills_dir, exist_ok=True)

    injected = {}

    skills = compile_all_skills(conn)
    for cat_key, content in skills.items():
        filename = f"helicon-{cat_key}.md"
        path = os.path.join(skills_dir, filename)
        with open(path, "w") as f:
            f.write(content)
        injected[filename] = len(content)

    core = compile_core_memory(conn)
    core_path = os.path.join(skills_dir, "helicon-core-memory.md")
    with open(core_path, "w") as f:
        f.write(core)
    injected["helicon-core-memory.md"] = len(core)

    return {
        "skills_dir": skills_dir,
        "files_injected": len(injected),
        "files": injected,
    }
